site_name: Movimiento Animal
#site_url: https://pvilas.github.io/animal-movements/
site_url: http://movimiento-animal.es/
site_description: Compilación de movimientos animales con detalles de cada ejercicio, rutinas, etc.
site_author: Pere Vilás (https://github.com/pvilas)
copyright: Pere Vilás
extra:
    version: 1.0
    unit:
        price: 12.50
theme:
    name: material
    language: es
    custom_dir: overrides
    logo: img/logo.png
plugins:
  - macros    
video:
    width: 640
    height: 360
    muted: 'muted'
copyright: '@Pere Vilás (<a href="http://pvilas.com" target="_blank">pvilas.com</a>)'
nav:
- Home : 'index.md'
- Calentar:
    - 'El calentamiento' : 'calentar/index.md'
    - 'Pies y tobillos' : 'calentar/pies.md'
    - 'Rodillas' : 'calentar/rodillas.md'
    - 'Caderas' : 'calentar/caderas.md'
    - 'Brazos' : 'calentar/brazos.md'
    - 'Cuello' : 'calentar/cuello.md'
    # - 'Espina' : 'calentar/espina.md'
- Ejercicios:
    - 'Push Up': 'ejercicios/pushup.md'
    - 'El arquero': 'ejercicios/arquero.md'
    - 'El arquero bajo' : 'ejercicios/arquero_bajo.md'
    - 'Hanuman Dand' : 'ejercicios/pushup_pie_adelantado.md'
    - 'Drill para lizard' : 'ejercicios/drill_para_lizard.md'
    - 'Pushup un brazo': 'ejercicios/pushup-un-brazo.md'
    - 'Pushup combo': 'ejercicios/pushup-combo.md'    
    - 'Flexión hindú' : 'ejercicios/flexion-hindu.md'
    - 'La pica' : 'ejercicios/la-pica.md'
    - 'Levantamiento de pies' : 'ejercicios/levantamiento.md'    
- Animales:
    - 'Los animales': 'animales/index.md'
    - 'El gatito': 'animales/gatito.md'
    - 'Araña frontal': 'animales/aranya-frontal.md'
    - 'Araña lateral': 'animales/aranya-lateral.md'
    - 'El caimán': 'animales/soldado.md'
    - 'El chimpancé': 'animales/chimpance.md'
    - 'Lagartija alta' : 'animales/high_lizard.md'
    - 'La lagartija' : 'animales/lizard.md'
    - Gambas:
        - 'Las gambas': 'animales/gambas/index.md'
        - 'Gamba hacia atrás': 'animales/gambas/gamba-atras.md'
        - 'Gamba hacia adelante': 'animales/gambas/gamba-adelante.md'
        - 'Gamba lateral': 'animales/gambas/gamba-de-lado.md'
        - 'Omote Sankaku': 'animales/gambas/gamba-triangulo.md'
        - 'Gamba saltarina': 'animales/gambas/balancin.md'
    - Cambios de base:            
        - 'Los cambios de base': 'animales/base/index.md'
    #    - 'Estirar hombros': 'animales/base/hombros.md'
    #    - 'Rotar': 'animales/base/rotar.md'
- Enfriar:
    - 'El enfriamiento' : 'enfriar/index.md'
    - 'El pino' : 'enfriar/pino.md'
    - 'Psoas' : 'enfriar/psoas.md'
    - 'Sarvangasana' : 'enfriar/sarvangasana.md'    
    - 'Sirsasana' : 'enfriar/sirsasana.md'
- Plantillas:
    - 'Plantilla de ejercicio': 'plantillas/ejercicio.md'    
- Varios:    
    # - 'Notas': 'varios/notas.md'
    - 'Recopilación inicial': 'varios/recopilacion.md'
    # - 'Mkdocs': 'varios/mkdocs.md'
    - 'Fuentes': 'varios/fuentes.md'
    - 'Entorno': 'varios/variables.md'