site_name: Movimientos Animales
site_description: Compilaci칩n de movimientos animales con detalles de cada ejercicio, rutinas, etc.
site_author: Pere Vil치s (https://github.com/pvilas)
copyright: Pere Vil치s
extra:
    version: 1.0
theme:
    name: material
    language: es
pages:
- Home : 'index.md'
- Plantillas:
    - 'Plantilla de ejercicio': 'plantillas/ejercicio.md'
- Varios:    
    - 'Notas': 'varios/notas.md'
    - 'Recopilaci칩n inicial': 'varios/recopilacion.md'
    - 'Mkdocs': 'varios/mkdocs.md'