site_name: Movimientos Animales
site_description: Compilación de movimientos animales con detalles de cada ejercicio, rutinas, etc.
site_author: Pere Vilás (https://github.com/pvilas)
copyright: Pere Vilás
extra:
    version: 1.0
theme:
    name: material
    language: es
    custom_dir: overrides
    logo: img/logo.png
plugins:
  - macros    
video:
    width: 640
    height: 360
copyright: '@Pere Vilás (<a href="http://pvilas.com" target="_blank">pvilas.com</a>)'
extra:
  unit:
    price: 12.50
nav:
- Home : 'index.md'
- Ejercicios:
    - 'El chimpancé': 'ejercicios/chimpance.md'

- Plantillas:
    - 'Plantilla de ejercicio': 'plantillas/ejercicio.md'
- Varios:    
    - 'Notas': 'varios/notas.md'
    - 'Recopilación inicial': 'varios/recopilacion.md'
    - 'Mkdocs': 'varios/mkdocs.md'
    - 'Fuentes': 'varios/fuentes.md'
    - 'Entorno': 'varios/variables.md'